[package]
name = "physx_rs"
version = "0.0.1"
authors = ["yangfeng <yangfengzzz@hotmail.com>"]
edition = "2018"
description = "A Physx port to Rust"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
